// server/_fixtures/codebase/nuxt-app/pages/login.vue
<template>
  <form data-testid="login-form" @submit.prevent>
    <input type="email" name="email" data-testid="email-field" v-model="email" aria-label="Email" />
    <input type="password" name="password" data-testid="password-field" v-model="password" aria-label="Password" />
    <button type="submit" data-testid="submit-button">Sign in</button>
  </form>
</template>

<script setup>
import { ref } from "vue";
const email = ref("");
const password = ref("");
</script>

// server/_fixtures/codebase/svelte-app/src/routes/login/+page.svelte
<script>
  let email = "";
  let password = "";
</script>

<form data-testid="login-form" on:submit|preventDefault>
  <input type="email" name="email" data-testid="email-field" bind:value={email} aria-label="Email" />
  <input type="password" name="password" data-testid="password-field" bind:value={password} aria-label="Password" />
  <button type="submit" data-testid="submit-button">Sign in</button>
</form>
