// server/_fixtures/codebase/svelte-app/src/routes/login/+page.svelte
<script>
  let email = "";
  let password = "";
</script>

<form data-testid="login-form" on:submit|preventDefault>
  <input type="email" name="email" data-testid="email-field" bind:value={email} aria-label="Email" />
  <input type="password" name="password" data-testid="password-field" bind:value={password} aria-label="Password" />
  <button type="submit" data-testid="submit-button">Sign in</button>
</form>

// server/_fixtures/codebase/next-app/app/login/page.tsx
"use client";
import { useState } from "react";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  return (
    <form data-testid="login-form" onSubmit={() => {}}>
      <input type="email" name="email" data-testid="email-field" aria-label="Email" value={email} onChange={(e) => setEmail(e.target.value)} />
      <input type="password" name="password" data-testid="password-field" aria-label="Password" value={password} onChange={(e) => setPassword(e.target.value)} />
      <button type="submit" data-testid="submit-button">Sign in</button>
    </form>
  );
}
